# Generated by Django 6.0.1 on 2026-01-27 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=False)),
                ('items_per_page', models.PositiveIntegerField(default=25)),
                ('receive_weekly_summary', models.BooleanField(default=True)),
                ('weekly_summary_email', models.EmailField(blank=True, max_length=254)),
                ('weekly_summary_day', models.PositiveSmallIntegerField(default=4)),
                ('weekly_summary_time', models.TimeField(default='16:00')),
                ('reminder_notifications', models.BooleanField(default=True)),
                ('overdue_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
