# Generated by Django 5.2.10 on 2026-04-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='All Around Town Outdoor Services', max_length=255)),
                ('address', models.CharField(default='Davenport, Iowa', max_length=500)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=7.0, max_digits=5)),
                ('invoice_prefix', models.CharField(default='INV-', max_length=20)),
                ('invoice_terms', models.TextField(default='Payment due within 15 days of invoice date. Late payments subject to 1.5% monthly interest.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
            },
        ),
    ]
