# Generated by Django 5.2.10 on 2026-02-14 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('cities_scanned', models.IntegerField(default=0)),
                ('total_results', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('keyword', models.CharField(max_length=100)),
                ('snippet', models.TextField(max_length=300)),
                ('source_url', models.URLField(max_length=500)),
                ('page_title', models.CharField(blank=True, default='', max_length=300)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF')], default='html', max_length=4)),
                ('found_at', models.DateTimeField(auto_now_add=True)),
                ('scan_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scanner.scanjob')),
            ],
            options={
                'ordering': ['-found_at'],
                'indexes': [models.Index(fields=['city', 'state'], name='scanner_sca_city_6c7fc0_idx'), models.Index(fields=['keyword'], name='scanner_sca_keyword_fbf5f5_idx')],
            },
        ),
    ]
