# Generated by Django 5.2.10 on 2026-04-10 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_increase_field_lengths'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(db_index=True, max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, default='IA', max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('hoa', 'HOA'), ('municipal', 'Municipal')], default='commercial', max_length=15)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('chamber_of_commerce', 'Chamber of Commerce'), ('new_llc', 'New LLC Filing'), ('building_permits', 'Building Permits'), ('google_maps', 'Google Maps'), ('referral', 'Referral'), ('municipal_rfp', 'Municipal RFP'), ('property_mgmt', 'Property Management'), ('cold_outreach', 'Cold Outreach'), ('news_announcement', 'News / Announcement')], default='cold_outreach', max_length=25)),
                ('source_detail', models.TextField(blank=True)),
                ('score', models.IntegerField(default=3, help_text='1-5 hot score')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('quoted', 'Quoted'), ('converted', 'Converted'), ('not_interested', 'Not Interested')], db_index=True, default='new', max_length=20)),
                ('services_needed', models.JSONField(blank=True, default=list)),
                ('last_contacted', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_leads', to='customers.customer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['status', '-score'], name='customers_l_status_20ecb1_idx'), models.Index(fields=['city', 'state'], name='customers_l_city_047afa_idx')],
            },
        ),
    ]
