# Generated by Django 6.0.1 on 2026-01-27 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('is_calendar_event', models.BooleanField(default=False)),
                ('default_duration_minutes', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('outcome', models.CharField(choices=[('completed', 'Completed'), ('no_answer', 'No Answer'), ('left_message', 'Left Message'), ('callback_requested', 'Callback Requested'), ('not_interested', 'Not Interested'), ('interested', 'Interested'), ('follow_up_needed', 'Follow Up Needed'), ('other', 'Other')], default='completed', max_length=20)),
                ('activity_datetime', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='customers.customer')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='activities.activitytype')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-activity_datetime'],
                'indexes': [models.Index(fields=['customer', '-activity_datetime'], name='activities__custome_eb2775_idx'), models.Index(fields=['-activity_datetime'], name='activities__activit_4e845a_idx')],
            },
        ),
    ]
